apiVersion: v1
kind: Namespace
metadata:
  name: apps-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: otel
---
apiVersion: v1
kind: Namespace
metadata:
  name: security